### ISSUE TITLE
AppendM2MData Doesn't include the Entity Attributes in the Package

### ISSUE THREAD

**Issue by dylanhaskins** [abvogel/Microsoft.Xrm.DevOps.Data#7]
Love the work you are doing with this :), the current             
if (HasManyToManyAttribute(fetchXml))
                {
                    this.AppendM2MData(retrieveMultipleResponse.EntityCollection, GetFirstLinkEntityName(fetchXml));
                }

results in an export that only includes the primary entity id but none of the other attributes specified in the FetchXML.

**Comment by abvogel** [comment]
Thanks! I'm super excited about the project and the potential!

Thanks for raising the issue - coincidentally came across the same thing today while testing a delta push of USD changes between environments.

**Comment by dylanhaskins** [comment]
Likewise, feel free to shout out if you need any testing help, starting to use it for some ALM bits, which is where it shines, as the manual configuration migration step historically was a barrier.
Currently this issue is the only one preventing me right now from using it, but almost there 😉


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by HIREN-AITC** [comment]
I have a data_schema.xml file from USD installation package. I want to use this file to export USD data to import into other environments through the pipeline. Is there any way I can use my data_schema.xml file to export the data? And yes, I came to this issue because I am also facing the same M2M relationship data inclusion issue.

**Comment by abvogel** [comment]
Currently the tool is driven from fetches - so that data_schema.xml file could be converted into a series of fetches that represent USD data. I'm going to reference your comment in another issue because being able to drive this from a schema.xml file would be a nice feature to have.

I'll try to add a few unit tests for M2M and get an official release out with support soon.

**Comment by HIREN-AITC** [comment]
> Currently the tool is driven from fetches - so that data_schema.xml file could be converted into a series of fetches that represent USD data. I'm going to reference your comment in another issue because being able to drive this from a schema.xml file would be a nice feature to have.
> 
> I'll try to add a few unit tests for M2M and get an official release out with support soon.

Thanks for your prompt response, hope to see the new release soon.

**Comment by dylanhaskins** [comment]
Hey Andrew, 

Any indication of timeline for committing this fix ?

Thanks in advance.

**Comment by abvogel** [comment]
v1.3.0 includes stub records for related m2m records - reflexive and otherwise.
